"""changing date to date type

Revision ID: 68e4c1b27ef3
Revises: 80af14aabcba
Create Date: 2025-06-09 17:45:43.825525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68e4c1b27ef3'
down_revision: Union[str, None] = '80af14aabcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE book
        ALTER COLUMN published_date TYPE DATE
        USING published_date::date;
    """)
    
    op.alter_column('book', 'published_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE book
        ALTER COLUMN published_date TYPE VARCHAR;
    """)

    op.alter_column('book', 'published_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
